/*
***************************************************************
*                       INCLUDES.H
***************************************************************
*/
#include    "D:\borlandc\INCLUDE\STDIO.H"
#include    "D:\borlandc\INCLUDE\STRING.H"
#include    "D:\borlandc\INCLUDE\CTYPE.H"
#include    "D:\borlandc\INCLUDE\STDLIB.H"
#include    "D:\borlandc\INCLUDE\CONIO.H"
#include    "D:\borlandc\INCLUDE\DOS.H"
#include    "UCOS186C.H"
#include    "UCOS.H"
extern void interrupt (*OldTickISR)(void);
